server:
  port: 8081

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.exemplo-spring
      routing-key:
        producer: rk.producer.exemplo-spring
      dead-letter:
        producer: dl.producer.exemplo-spring
